service: parameter-store-sync

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  profile: ${opt:profile, 'personal'}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:PutParameter
            - ssm:DeleteParameter
            - ssm:GetParameter
            - ssm:GetParametersByPath
          Resource: 
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/dev/sendgrid_template_ids/*
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/dev/sendgrid_template_ids
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/prod/sendgrid_template_ids/*
            - arn:aws:ssm:${aws:region}:${aws:accountId}:parameter/prod/sendgrid_template_ids

functions:
  sync:
    handler: dist/index.handler
    environment:
      DEV_SENDGRID_VAULT_ID: ${env:DEV_SENDGRID_VAULT_ID}
      PROD_SENDGRID_VAULT_ID: ${env:PROD_SENDGRID_VAULT_ID}
      DEV_SENDGRID_ITEM_ID: ${env:DEV_SENDGRID_ITEM_ID}
      PROD_SENDGRID_ITEM_ID: ${env:PROD_SENDGRID_ITEM_ID}
      OP_SERVICE_ACCOUNT_TOKEN: ${env:OP_SERVICE_ACCOUNT_TOKEN}
    events:
      - schedule: rate(5 minutes)